In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
pwd

'/content'

In [4]:
ls

 drive/  'IMDB Dataset.csv'   sample_data/

In [5]:
data_path = 'IMDB Dataset.csv'

In [6]:
df = pd.read_csv(data_path)

In [7]:
df.shape

(50000, 2)

In [8]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [9]:
df = df.head(100)

In [10]:
df.shape

(100, 2)

In [11]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [12]:
df['review'] = df['review'].str.lower()

In [13]:
df

                                               review sentiment
0   one of the other reviewers has mentioned that ...  positive
1   a wonderful little production. <br /><br />the...  positive
2   i thought this was a wonderful way to spend ti...  positive
3   basically there's a family where a little boy ...  negative
4   petter mattei's "love in the time of money" is...  positive
..                                                ...       ...
95  daniel day-lewis is the most versatile actor a...  positive
96  my guess would be this was originally going to...  negative
97  well, i like to watch bad horror b-movies, cau...  negative
98  this is the worst movie i have ever seen, as w...  negative
99  i have been a mario fan for as long as i can r...  positive

[100 rows x 2 columns]

Remove HTML Tags

In [19]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [20]:
text = "<html><body><p> Movie 1</p><p> Actor - Aamir Khan</p><title> Home Page - 1 </title></body></html>"

In [21]:
remove_html_tags(text)

' Movie 1 Actor - Aamir Khan Home Page - 1 '

In [23]:
df['review'] = df['review'].apply(remove_html_tags)

In [24]:
df

                                               review sentiment
0   one of the other reviewers has mentioned that ...  positive
1   a wonderful little production. the filming tec...  positive
2   i thought this was a wonderful way to spend ti...  positive
3   basically there's a family where a little boy ...  negative
4   petter mattei's "love in the time of money" is...  positive
..                                                ...       ...
95  daniel day-lewis is the most versatile actor a...  positive
96  my guess would be this was originally going to...  negative
97  well, i like to watch bad horror b-movies, cau...  negative
98  this is the worst movie i have ever seen, as w...  negative
99  i have been a mario fan for as long as i can r...  positive

[100 rows x 2 columns]

Remove URL

In [25]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [26]:
text1 = 'Check out my youtube https://www.youtube.com/dswithbappy dswithbappy'
text2 = 'Check out my linkedin https://www.linkedin.com/in/boktiarahmed73/'
text3 = 'Google search here www.google.com'
text4 = 'For data click https://www.kaggle.com'

In [27]:
remove_url(text1)

'Check out my youtube  dswithbappy'

In [31]:
remove_url(text2)

'Check out my linkedin '

In [34]:
remove_url(text3)

'Google search here '

In [36]:
remove_url(text4)

'For data click '

Punctuation Handling

In [37]:
import string, time

In [38]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [39]:
exclude = string.punctuation

In [40]:
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [41]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char, '')
    return text

In [42]:
text = 'string . with. Punctuation?'

In [45]:
start = time.time()
print(remove_punc(text))
time1 = time.time() - start
print(time1*50000)

string  with Punctuation
8.83340835571289

In [46]:
def remove_punc1(text):
    return text.translate(str.maketrans('','',exclude))

In [47]:
start = time.time()
remove_punc1(text)
time2 = time.time() - start
print(time2*50000)

6.473064422607422

In [48]:
df['review'][5]

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

In [49]:
remove_punc1(df['review'][5])

'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'

In [51]:
df['review'] = df['review'].apply(remove_punc1)

In [52]:
df

                                               review sentiment
0   one of the other reviewers has mentioned that ...  positive
1   a wonderful little production the filming tech...  positive
2   i thought this was a wonderful way to spend ti...  positive
3   basically theres a family where a little boy j...  negative
4   petter matteis love in the time of money is a ...  positive
..                                                ...       ...
95  daniel daylewis is the most versatile actor al...  positive
96  my guess would be this was originally going to...  negative
97  well i like to watch bad horror bmovies cause ...  negative
98  this is the worst movie i have ever seen as we...  negative
99  i have been a mario fan for as long as i can r...  positive

[100 rows x 2 columns]

Chat Conversion Handle

In [53]:
chat_words = {
    'AFAIK':'As Far As I Know',
    'AFK':'Away From Keyboard',
    'ASAP':'As Soon As Possible',
    'ATK':'At The Keyboard',
    'ATM':'At The Moment'
}
chat_words

{'AFAIK': 'As Far As I Know',
 'AFK': 'Away From Keyboard',
 'ASAP': 'As Soon As Possible',
 'ATK': 'At The Keyboard',
 'ATM': 'At The Moment'}

In [54]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [55]:
chat_conversion('Do this Work ASAP')

'Do this Work As Soon As Possible'

Incorrect text Handling

In [56]:
from textblob import TextBlob

In [57]:
incorrect_text = 'ceertain conditionas duriing serval ggeneations aree modidfied in the samee maner'

textBlb = TextBlob(incorrect_text)

textBlb.correct().string

'certain conditions during several generations are modified in the same manner'

StopWords

In [59]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [60]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [61]:
len(stopwords.words('english'))

198

In [64]:
def remove_stopwords(text):
    new_text = []
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [65]:
remove_stopwords('probably my all time favorite move, a story of selflessnes, sacrifice and emotion')

'probably   time favorite move,  story  selflessnes, sacrifice  emotion'

In [66]:
df['review'] = df['review'].apply(remove_stopwords)

In [67]:
df

                                               review sentiment
0   one    reviewers  mentioned   watching  1 oz e...  positive
1    wonderful little production  filming techniqu...  positive
2    thought    wonderful way  spend time    hot s...  positive
3   basically theres  family   little boy jake thi...  negative
4   petter matteis love   time  money   visually s...  positive
..                                                ...       ...
95  daniel daylewis    versatile actor alive engli...  positive
96   guess would    originally going    least two ...  negative
97  well  like  watch bad horror bmovies cause  th...  negative
98     worst movie   ever seen  well   worst    pr...  negative
99      mario fan   long    remember    fond memor...  positive

[100 rows x 2 columns]

Emoji Removal

In [68]:
import re

In [69]:
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U0001F251"
                           "]+", flags = re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [70]:
remove_emoji("Loved the movie. It was 😘😘")

'Loved the movie. It was '

In [71]:
pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 5.2 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [72]:
import emoji

In [73]:
print(emoji.demojize('Python is 🔥'))

Python is :fire:

Tokenization

1. Using the Split Function

In [76]:
# word tokenization
sent1 = 'I am going to Delhi'
sent1.split()

['I', 'am', 'going', 'to', 'Delhi']

In [77]:
# sentence tokenization
sent2 = 'I am going to delhi. I will stay there for 3 days. lets hope the trip to be great'
sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 ' lets hope the trip to be great']

2. Regular Expression

In [80]:
import re
sent3 = 'I am going to delhi!'
tokens = re.findall("[\w']+", sent3)
tokens

<>:3: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_6997/3190589682.py:3: SyntaxWarning: invalid escape sequence '\w'
  tokens = re.findall("[\w']+", sent3)

['I', 'am', 'going', 'to', 'delhi']